CXX=clang++ 
CXXFLAGS=-Wall # Enable all warnings                                            
DEBUG=-g

OFILES = AVLTree.o AVLNode.o AVLPathTest.o

.SUFFIXES: .o .cpp

.PHONY: main clean

main: $(OFILES)
	$(CXX) $(CXXFLAGS) $(OFILES)


clean:
	-rm *.o a.out





